// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import './globals.css'
// import AuthProvider from "@/context/AuthProvider";
// import { Toaster } from "@/components/ui/sonner"
// import Navbar from "@/components/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <AuthProvider>

//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
//         <Navbar/>
//         {children}
//         <Toaster/>
//       </body>
      
//       </AuthProvider>
//     </html>
//   );
// }





"use client";

import { usePathname } from "next/navigation";
import Navbar from "@/components/Navbar";
import { Toaster } from "@/components/ui/sonner";
import { Geist, Geist_Mono } from "next/font/google";
import AuthProvider from "@/context/AuthProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();

  // Dynamic route check: agar path /u/ se start hota hai, navbar hide kar do
  const shouldHideNavbar = pathname.startsWith("/u/");

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          {!shouldHideNavbar && <Navbar />}
          <main className="min-h-screen">{children}</main>
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
